#index:
#    path: /
#    controller: App\Controller\DefaultController::index

admin: 
    path: /admin
    controller: App\Controller\HomeController::index
liste:
    path: /user
    controller: App\Controller\UserController::index
panneau: 
    path: /panneau
    controller: App\Controller\PanneauxController::index
ticket: 
    path: /ticket
    controller: App\Controller\TicketController::index
panneaux: 
    path: /pannea/add
    controller: App\Controller\PanneauxController::add
